POST http://localhost:3005/api/signup
Content-Type: application/json

{
    "firstName":"4234fsdfs",
    "Email":"m,dfg,m,m.123@gmail.com",
    "password":"kmmookoko",      
    "phoneNumber":"9865457708"
      
}